#!/usr/bin/env python3
"""bundle_decomposer.py — produce a standalone diag_repro_decomposer.

Reads:
  - corp_diag_lib.py
  - diag_repro_decomposer.py

Writes:
  - diag_repro_decomposer_bundled.py

The bundled file embeds corp_diag_lib as an inline source string, exec'd
into a synthetic ``lib`` module at startup. All the diag's existing
``lib.X`` references continue to work unchanged.

Why single-file: lets you copy ONE python file to a corp box (plus
optionally a yaml config) instead of the whole apim-diag directory.

Re-run whenever corp_diag_lib.py or diag_repro_decomposer.py changes.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).parent
LIB_PATH = ROOT / "corp_diag_lib.py"
DIAG_PATH = ROOT / "diag_repro_decomposer.py"
OUT_PATH = ROOT / "diag_repro_decomposer_bundled.py"


def main() -> int:
    lib_src = LIB_PATH.read_text(encoding="utf-8")
    diag_src = DIAG_PATH.read_text(encoding="utf-8")

    # `from __future__ import` must be the FIRST executable statement in a
    # python module. The bundled file needs one at its own top, AND we must
    # strip any future-imports from the diag body (otherwise SyntaxError —
    # mid-file future imports are illegal).
    #
    # The lib body's future-imports are fine: they sit at the top of the
    # exec'd string, which is its own compilation unit.
    diag_src = re.sub(
        r"^from __future__ import [^\n]*\n",
        "# (from __future__ moved to bundle top)\n",
        diag_src,
        flags=re.MULTILINE,
    )

    # Strip the `import corp_diag_lib as lib` line — the lib namespace is
    # created via exec in the bundled prelude.
    diag_src = re.sub(
        r"^import corp_diag_lib as lib\s*\n",
        "# (corp_diag_lib embedded via exec in bundled prelude above)\n",
        diag_src,
        count=1,
        flags=re.MULTILINE,
    )

    bundled = (
        '"""diag_repro_decomposer (BUNDLED single-file edition).\n'
        "\n"
        "Auto-generated by bundle_decomposer.py from:\n"
        "  - corp_diag_lib.py\n"
        "  - diag_repro_decomposer.py\n"
        "\n"
        "Do NOT edit this file directly. Edit the source files and re-run\n"
        "bundle_decomposer.py instead.\n"
        '"""\n'
        "from __future__ import annotations\n"
        "\n"
        "# ============================================================================\n"
        "# Inline corp_diag_lib — exec'd into a fresh module namespace so the diag's\n"
        "# existing `lib.X` references work unchanged.\n"
        "# ============================================================================\n"
        "import sys as _sys\n"
        "import types as _types\n"
        "\n"
        f"_CORP_DIAG_LIB_SOURCE = {lib_src!r}\n"
        "\n"
        "lib = _types.ModuleType('corp_diag_lib')\n"
        "# Register BEFORE exec so dataclass / pydantic forward-ref resolution\n"
        "# (which looks up sys.modules[cls.__module__]) finds our synthetic module.\n"
        "_sys.modules['corp_diag_lib'] = lib\n"
        "# Pin lib's __file__ to THIS bundle's location so the lib's yaml-discovery\n"
        "# (Path(__file__).parent walk) finds corp_diag_config.yaml next to the bundle.\n"
        "lib.__file__ = __file__\n"
        "exec(compile(_CORP_DIAG_LIB_SOURCE, 'corp_diag_lib.py', 'exec'), lib.__dict__)\n"
        "\n"
        "# ============================================================================\n"
        "# diag_repro_decomposer body (verbatim, with `from __future__` and `import\n"
        "# corp_diag_lib` stripped — both handled by the prelude above).\n"
        "# ============================================================================\n"
        "\n"
        f"{diag_src}"
    )

    OUT_PATH.write_text(bundled, encoding="utf-8")
    n_lib = len(lib_src.splitlines())
    n_diag = len(diag_src.splitlines())
    n_out = len(bundled.splitlines())
    print(f"Wrote {OUT_PATH}")
    print(f"  embedded lib  : {n_lib} lines / {len(lib_src):,} bytes")
    print(f"  embedded diag : {n_diag} lines / {len(diag_src):,} bytes")
    print(f"  bundled output: {n_out} lines / {len(bundled):,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
